[project]
name = "video-data-catalog"
version = "0.1.0"
description = "Video data catalog"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "redis[hiredis]>=6.2.0",
    "typer>=0.15.2",
]

[dependency-groups]
dev = [
    "mypy>=1.17.0",
]
